import axiosInstance from "../utils/axiosInstance";

export const dueRequestAPI = {
  // Get all due requests based on user role
  getDueRequestsForApprover: async (filters = {}) => {
    try {
      const { userType, adminId, franchiseId, driverId, status, type } = filters;
      let url = "/dueRequest";

      // Add query parameters based on backend requirements
      const params = new URLSearchParams();
      if (userType) params.append("userType", userType);
      if (adminId) params.append("adminId", adminId);
      if (franchiseId) params.append("franchiseId", franchiseId);
      if (driverId) params.append("driverId", driverId);
      if (status) params.append("status", status);
      if (type) params.append("type", type);

      if (params.toString()) {
        url += `?${params.toString()}`;
      }

      const response = await axiosInstance.get(url);
      return response.data;
    } catch (error) {
      console.error("Error fetching due requests:", error);
      throw error;
    }
  },

  // Create driver due request
  createDriverDueRequest: async (data) => {
    try {
      const response = await axiosInstance.post("/dueRequest", data);
      return response.data;
    } catch (error) {
      console.error("Error creating driver due request:", error);
      throw error;
    }
  },

  // Create franchise due request for weekly bill
  createFranchiseDueRequest: async (franchiseId, data) => {
    try {
      const response = await axiosInstance.post(
        `/dueRequest/franchise/${franchiseId}`,
        data
      );
      return response.data;
    } catch (error) {
      console.error("Error creating franchise due request:", error);
      throw error;
    }
  },

  // Approve due request
  approveDueRequest: async (dueRequestId, data) => {
    try {
      const response = await axiosInstance.patch(
        `/dueRequest/${dueRequestId}/approve`,
        data
      );
      return response.data;
    } catch (error) {
      console.error("Error approving due request:", error);
      throw error;
    }
  },

  // Get statistics
  getStatistics: async (filters = {}) => {
    try {
      const { userType, adminId, franchiseId, driverId, startDate, endDate } = filters;
      let url = "/dueRequest/statistics";

      const params = new URLSearchParams();
      if (userType) params.append("userType", userType);
      if (adminId) params.append("adminId", adminId);
      if (franchiseId) params.append("franchiseId", franchiseId);
      if (driverId) params.append("driverId", driverId);
      if (startDate) params.append("startDate", startDate);
      if (endDate) params.append("endDate", endDate);

      if (params.toString()) {
        url += `?${params.toString()}`;
      }

      const response = await axiosInstance.get(url);
      return response.data;
    } catch (error) {
      console.error("Error fetching statistics:", error);
      throw error;
    }
  },

  // Get due request by ID
  getDueRequestById: async (dueRequestId) => {
    try {
      const response = await axiosInstance.get(`/dueRequest/${dueRequestId}`);
      return response.data;
    } catch (error) {
      console.error("Error fetching due request details:", error);
      throw error;
    }
  },

  // Get franchise pending bills (for manual due request creation)
  getFranchisePendingBills: async (franchiseId) => {
    try {
      const response = await axiosInstance.get(
        `/dueRequest/franchise/${franchiseId}/pending-bills`
      );
      return response.data;
    } catch (error) {
      console.error("Error fetching franchise pending bills:", error);
      throw error;
    }
  },

  // Get franchise due request history
  getFranchiseDueRequestHistory: async (franchiseId, filters = {}) => {
    try {
      const { status, limit, page, startDate, endDate } = filters;
      let url = `/dueRequest/franchise/${franchiseId}/history`;

      const params = new URLSearchParams();
      if (status) params.append("status", status);
      if (limit) params.append("limit", limit);
      if (page) params.append("page", page);
      if (startDate) params.append("startDate", startDate);
      if (endDate) params.append("endDate", endDate);

      if (params.toString()) {
        url += `?${params.toString()}`;
      }

      const response = await axiosInstance.get(url);
      return response.data;
    } catch (error) {
      console.error("Error fetching franchise due request history:", error);
      throw error;
    }
  },

  // Get franchise billing dashboard
  getFranchiseBillingDashboard: async (franchiseId) => {
    try {
      const response = await axiosInstance.get(
        `/dueRequest/franchise/${franchiseId}/dashboard`
      );
      return response.data;
    } catch (error) {
      console.error("Error fetching franchise billing dashboard:", error);
      throw error;
    }
  },

  // Get admin auto-generated bills
  getAdminAutoGeneratedBills: async (filters = {}) => {
    try {
      const { status, franchiseId, limit, page, startDate, endDate } = filters;
      let url = "/dueRequest/admin/bills";

      const params = new URLSearchParams();
      if (status) params.append("status", status);
      if (franchiseId) params.append("franchiseId", franchiseId);
      if (limit) params.append("limit", limit);
      if (page) params.append("page", page);
      if (startDate) params.append("startDate", startDate);
      if (endDate) params.append("endDate", endDate);

      if (params.toString()) {
        url += `?${params.toString()}`;
      }

      const response = await axiosInstance.get(url);
      return response.data;
    } catch (error) {
      console.error("Error fetching admin auto-generated bills:", error);
      throw error;
    }
  },

  // Upload payment image to Cloudinary
  uploadPaymentImage: async (imageFile) => {
    try {
      const formData = new FormData();
      formData.append("file", imageFile);
      formData.append("upload_preset", "EtoAdmin_payemntPhotoUpload");
      formData.append("cloud_name", "dswrynlti");

      const response = await axiosInstance.post(
        "https://api.cloudinary.com/v1_1/dswrynlti/image/upload",
        formData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );
      return response.data.secure_url;
    } catch (error) {
      console.error("Error uploading payment image:", error);
      throw error;
    }
  },
};